<?xml version="1.0"?>
<package format="3">
  <name>racer_core</name>
  <version>0.1.0</version>
  <description>ROS-independent Python implementation of RACER algorithms.</description>
  <maintainer email="kong-huihui@users.noreply.github.com">Kong-huihui</maintainer>
  <license>LicenseRef-RACER-Upstream</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
