#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export RACER_FIDELITY_HEADLESS=0
export RACER_FIDELITY_VISUALIZE=1
export RACER_FIDELITY_DRONE_COUNT="${RACER_FIDELITY_DRONE_COUNT:-5}"
export RACER_FIDELITY_DURATION="${RACER_FIDELITY_DURATION:-900}"
export RACER_INTERACTIVE_RENDER_HZ="${RACER_INTERACTIVE_RENDER_HZ:-30}"
export RACER_VISUALIZATION_MAX_MAP_POINTS="${RACER_VISUALIZATION_MAX_MAP_POINTS:-12000}"
exec "${script_dir}/run_warehouse_simple.sh"
