cmake_minimum_required(VERSION 3.8)
project(racer_3d_interfaces)

find_package(ament_cmake REQUIRED)
find_package(builtin_interfaces REQUIRED)
find_package(rosidl_default_generators REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/CommPacket.msg"
  "msg/LinkQuality.msg"
  "msg/LinkQualityArray.msg"
  "msg/CommStatistics.msg"
  DEPENDENCIES builtin_interfaces
)

ament_export_dependencies(rosidl_default_runtime)
ament_package()
